version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tool_testing_db
    command: ["postgres", "-c", "port=6000"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      PGPORT: 6000
    ports:
      - "6000:6000"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tool_testing_backend
    environment:
      # Connects to the dockerized database
      - DATABASE_URL=postgresql://postgres:12345@db:6000/postgres?schema=tool-test-api
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tool_testing_frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data:
