// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/25/2026, 9:19:44 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/My Project/tool-testing-api/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/My Project/tool-testing-api/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/My Project/tool-testing-api/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/My Project/tool-testing-api/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/My Project/tool-testing-api/frontend/plugins/**/*.{js,ts,mjs}","D:/My Project/tool-testing-api/frontend/composables/**/*.{js,ts,mjs}","D:/My Project/tool-testing-api/frontend/utils/**/*.{js,ts,mjs}","D:/My Project/tool-testing-api/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/My Project/tool-testing-api/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/My Project/tool-testing-api/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/My Project/tool-testing-api/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;